# Generated by Django 5.2.17 on 2026-09-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('SIMULATED', 'Simulated (Mock)'), ('PENDING', 'Pending Device Ack'), ('SUCCESS', 'Success'), ('ERROR', 'Error')], default='SIMULATED', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
