# Generated by Django 5.2.17 on 2026-09-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_devicecommand'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='READY', max_length=20)),
                ('expression', models.CharField(default='NEUTRAL', max_length=20)),
                ('eye_style', models.CharField(default='ROUND', max_length=20)),
                ('animation', models.CharField(default='IDLE', max_length=20)),
                ('display_text', models.CharField(default='Ready to assist', max_length=255)),
                ('brightness', models.IntegerField(default=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
