# Generated by Django 5.2.17 on 2026-10-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_companionstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkProvisioningState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('UNPROVISIONED', 'Unprovisioned'), ('SETUP_AP', 'Setup access point'), ('CONNECTING', 'Connecting'), ('FAILED', 'Failed'), ('NORMAL_MODE', 'Normal mode')], default='UNPROVISIONED', max_length=20)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
