# Generated by Django 5.2.17 on 2026-09-14 16:46

import knowledge_base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=knowledge_base.models.document_upload_path)),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Indexing'), ('INDEXED', 'Indexed'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
            ],
        ),
    ]
