"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-default-key-for-dev')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party
    'rest_framework',
    
    # Local apps
    'dashboard',
    'assistant',
    'conversations',
    'knowledge_base',
    'system',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dashboard.context_processors.system_status',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AI Engine Configuration
# Supported values: 'mock' (default), 'local' (requires Ollama)
AI_ENGINE = os.environ.get('AI_ENGINE', 'mock')

# Ollama configuration (only used when AI_ENGINE=local)
OLLAMA_HOST = os.environ.get('OLLAMA_HOST', 'http://localhost:11434')
OLLAMA_MODEL = os.environ.get('OLLAMA_MODEL', 'llama3.2:1b')
OLLAMA_TIMEOUT = int(os.environ.get('OLLAMA_TIMEOUT', '120'))
CHAT_REQUEST_TIMEOUT_SECONDS = int(os.environ.get('CHAT_REQUEST_TIMEOUT_SECONDS', '30'))

# Offline local knowledge / RAG
RAG_ENABLED = os.environ.get('RAG_ENABLED', 'false').lower() in ('1', 'true', 'yes', 'on')
RAG_RETRIEVER = os.environ.get('RAG_RETRIEVER', 'lexical')
RAG_CHUNK_CHARS = int(os.environ.get('RAG_CHUNK_CHARS', '1000'))
RAG_CHUNK_OVERLAP_CHARS = int(os.environ.get('RAG_CHUNK_OVERLAP_CHARS', '150'))
RAG_TOP_K = int(os.environ.get('RAG_TOP_K', '4'))
RAG_MIN_RELEVANCE = float(os.environ.get('RAG_MIN_RELEVANCE', '0.5'))

# Optional online retrieval. Generation remains on the configured local LLM.
ONLINE_RETRIEVAL_ENABLED = os.environ.get('ONLINE_RETRIEVAL_ENABLED', 'false').lower() in ('1', 'true', 'yes', 'on')
ONLINE_PROVIDER = os.environ.get('ONLINE_PROVIDER', 'searxng')
ONLINE_TIMEOUT_SECONDS = float(os.environ.get('ONLINE_TIMEOUT_SECONDS', '8'))
ONLINE_MAX_RESULTS = int(os.environ.get('ONLINE_MAX_RESULTS', '4'))
ONLINE_MAX_CONTEXT_CHARS = int(os.environ.get('ONLINE_MAX_CONTEXT_CHARS', '6000'))
SEARXNG_BASE_URL = os.environ.get('SEARXNG_BASE_URL', 'http://127.0.0.1:8888')

# Optional ESP32 action/sensor integration over a local MQTT broker.
DEVICE_CONTROL_ENABLED = os.environ.get('DEVICE_CONTROL_ENABLED', 'false').lower() in ('1', 'true', 'yes', 'on')
DEVICE_TRANSPORT = os.environ.get('DEVICE_TRANSPORT', 'mqtt')
MQTT_HOST = os.environ.get('MQTT_HOST', '127.0.0.1')
MQTT_PORT = int(os.environ.get('MQTT_PORT', '1883'))
MQTT_KEEPALIVE = int(os.environ.get('MQTT_KEEPALIVE', '30'))
MQTT_COMMAND_TIMEOUT_SECONDS = float(os.environ.get('MQTT_COMMAND_TIMEOUT_SECONDS', '5'))
MQTT_TOPIC_PREFIX = os.environ.get('MQTT_TOPIC_PREFIX', 'smart-companion')
ESP32_DEVICE_ID = os.environ.get('ESP32_DEVICE_ID', '')

# Voice Engine Configuration
STT_ENGINE = os.environ.get('STT_ENGINE', 'mock')
STT_WHISPER_BIN = os.environ.get('STT_WHISPER_BIN', '/opt/whisper.cpp/main')
STT_WHISPER_MODEL = os.environ.get('STT_WHISPER_MODEL', '/opt/whisper.cpp/models/ggml-base.en.bin')
STT_TIMEOUT = int(os.environ.get('STT_TIMEOUT', '30'))
STT_VAD_ENABLED = os.environ.get('STT_VAD_ENABLED', 'false').lower() in ('1', 'true', 'yes', 'on')
STT_VAD_MODEL = os.environ.get('STT_VAD_MODEL', '')
STT_VAD_THRESHOLD = float(os.environ.get('STT_VAD_THRESHOLD', '0.5'))
STT_VAD_MIN_SPEECH_MS = int(os.environ.get('STT_VAD_MIN_SPEECH_MS', '250'))
STT_VAD_MIN_SILENCE_MS = int(os.environ.get('STT_VAD_MIN_SILENCE_MS', '700'))
STT_VAD_SPEECH_PAD_MS = int(os.environ.get('STT_VAD_SPEECH_PAD_MS', '100'))

TTS_ENGINE = os.environ.get('TTS_ENGINE', 'mock')
TTS_PIPER_BIN = os.environ.get('TTS_PIPER_BIN', '/opt/piper/piper')
TTS_PIPER_VOICE = os.environ.get('TTS_PIPER_VOICE', '/opt/piper/en_US-lessac-medium.onnx')
TTS_TIMEOUT = int(os.environ.get('TTS_TIMEOUT', '30'))

# Standalone Raspberry Pi voice loop
VOICE_INPUT_SOURCE = os.environ.get('VOICE_INPUT_SOURCE', '')
VOICE_RECORD_SECONDS = os.environ.get('VOICE_RECORD_SECONDS', '5')
VOICE_INPUT_WARMUP_SECONDS = os.environ.get('VOICE_INPUT_WARMUP_SECONDS', '1.0')
VOICE_CAPTURE_VAD_ENABLED = os.environ.get('VOICE_CAPTURE_VAD_ENABLED', 'false').lower() in ('1', 'true', 'yes', 'on')
VOICE_CAPTURE_VAD_START_THRESHOLD = os.environ.get('VOICE_CAPTURE_VAD_START_THRESHOLD', '0.02')
VOICE_CAPTURE_VAD_SILENCE_SECONDS = os.environ.get('VOICE_CAPTURE_VAD_SILENCE_SECONDS', '0.8')
VOICE_CAPTURE_VAD_MAX_SECONDS = os.environ.get('VOICE_CAPTURE_VAD_MAX_SECONDS', '10')
VOICE_CAPTURE_VAD_START_TIMEOUT_SECONDS = os.environ.get('VOICE_CAPTURE_VAD_START_TIMEOUT_SECONDS', '5')
VOICE_LEADING_SILENCE_SECONDS = os.environ.get('VOICE_LEADING_SILENCE_SECONDS', '0.7')
VOICE_TTS_CHUNK_CHARS = os.environ.get('VOICE_TTS_CHUNK_CHARS', '300')
VOICE_TTS_MAX_TOTAL_CHARS = os.environ.get('VOICE_TTS_MAX_TOTAL_CHARS', '0')
VOICE_LLM_BRIEF_NUM_PREDICT = os.environ.get('VOICE_LLM_BRIEF_NUM_PREDICT', '96')
VOICE_LLM_NORMAL_NUM_PREDICT = os.environ.get('VOICE_LLM_NORMAL_NUM_PREDICT', '160')
VOICE_LLM_DETAILED_NUM_PREDICT = os.environ.get('VOICE_LLM_DETAILED_NUM_PREDICT', '384')
