"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-default-key-for-dev')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get(
    'ALLOWED_HOSTS',
    'smart-ai-companion.local,127.0.0.1,localhost',
).split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party
    'rest_framework',
    
    # Local apps
    'dashboard',
    'assistant',
    'conversations',
    'knowledge_base',
    'system',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'system.middleware.SetupModeIsolationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dashboard.context_processors.system_status',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AI Engine Configuration
# Supported values: 'mock' (default), 'local' (requires Ollama)
AI_ENGINE = os.environ.get('AI_ENGINE', 'mock')

# Ollama configuration (only used when AI_ENGINE=local)
OLLAMA_HOST = os.environ.get('OLLAMA_HOST', 'http://localhost:11434')
OLLAMA_MODEL = os.environ.get('OLLAMA_MODEL', 'llama3.2:3b')
OLLAMA_TIMEOUT = int(os.environ.get('OLLAMA_TIMEOUT', '120'))
OLLAMA_KEEP_ALIVE = os.environ.get('OLLAMA_KEEP_ALIVE', '30m')
OLLAMA_NUM_PREDICT = int(os.environ.get('OLLAMA_NUM_PREDICT', '128'))
AI_LIGHTWEIGHT_MODEL = os.environ.get('AI_LIGHTWEIGHT_MODEL', 'llama3.2:1b')
AI_GENERATION_NORMAL_NUM_PREDICT = int(
    os.environ.get('AI_GENERATION_NORMAL_NUM_PREDICT', str(OLLAMA_NUM_PREDICT))
)
AI_GENERATION_REDUCED_NUM_PREDICT = int(os.environ.get('AI_GENERATION_REDUCED_NUM_PREDICT', '96'))
AI_GENERATION_MINIMAL_NUM_PREDICT = int(os.environ.get('AI_GENERATION_MINIMAL_NUM_PREDICT', '48'))
AI_CONTEXT_NORMAL_MESSAGES = int(os.environ.get('AI_CONTEXT_NORMAL_MESSAGES', '10'))
AI_CONTEXT_REDUCED_MESSAGES = int(os.environ.get('AI_CONTEXT_REDUCED_MESSAGES', '6'))
AI_CONTEXT_MINIMAL_MESSAGES = int(os.environ.get('AI_CONTEXT_MINIMAL_MESSAGES', '3'))
AI_LOCAL_GENERATION_TIMEOUT_SECONDS = float(
    os.environ.get('AI_LOCAL_GENERATION_TIMEOUT_SECONDS', str(OLLAMA_TIMEOUT))
)
CHAT_REQUEST_TIMEOUT_SECONDS = int(os.environ.get('CHAT_REQUEST_TIMEOUT_SECONDS', '30'))
CHAT_BACKEND_TIMEOUT_MARGIN_SECONDS = int(os.environ.get('CHAT_BACKEND_TIMEOUT_MARGIN_SECONDS', '15'))
CHAT_STREAM_IDLE_TIMEOUT_SECONDS = int(os.environ.get('CHAT_STREAM_IDLE_TIMEOUT_SECONDS', '45'))

# Conversation-scoped, local lexical memory; zero limits disable memory context.
CONVERSATION_RECENT_MESSAGES = int(os.environ.get('CONVERSATION_RECENT_MESSAGES', '4'))
CONVERSATION_MEMORY_TOP_K = int(os.environ.get('CONVERSATION_MEMORY_TOP_K', '2'))
CONVERSATION_MEMORY_MAX_CHARS = int(os.environ.get('CONVERSATION_MEMORY_MAX_CHARS', '400'))
CONVERSATION_MEMORY_MIN_RELEVANCE = float(os.environ.get('CONVERSATION_MEMORY_MIN_RELEVANCE', '0.5'))

# Offline local knowledge / RAG
RAG_ENABLED = os.environ.get('RAG_ENABLED', 'false').lower() in ('1', 'true', 'yes', 'on')
RAG_RETRIEVER = os.environ.get('RAG_RETRIEVER', 'lexical')
RAG_CHUNK_CHARS = int(os.environ.get('RAG_CHUNK_CHARS', '700'))
RAG_CHUNK_OVERLAP_CHARS = int(os.environ.get('RAG_CHUNK_OVERLAP_CHARS', '100'))
RAG_TOP_K = int(os.environ.get('RAG_TOP_K', '2'))
RAG_MODEL = os.environ.get('RAG_MODEL', AI_LIGHTWEIGHT_MODEL)
RAG_MAX_CONTEXT_CHARS = int(os.environ.get('RAG_MAX_CONTEXT_CHARS', '1200'))
RAG_NUM_PREDICT = int(os.environ.get('RAG_NUM_PREDICT', '64'))
RAG_PREWARM_ENABLED = os.environ.get('RAG_PREWARM_ENABLED', 'false').lower() in ('1', 'true', 'yes', 'on')
RAG_PREWARM_TIMEOUT_SECONDS = float(os.environ.get('RAG_PREWARM_TIMEOUT_SECONDS', '20'))
RAG_MIN_RELEVANCE = float(os.environ.get('RAG_MIN_RELEVANCE', '0.5'))

# Optional online retrieval. Generation remains on the configured local LLM.
ONLINE_RETRIEVAL_ENABLED = os.environ.get('ONLINE_RETRIEVAL_ENABLED', 'false').lower() in ('1', 'true', 'yes', 'on')
ONLINE_PROVIDER = os.environ.get('ONLINE_PROVIDER', 'searxng')
ONLINE_TIMEOUT_SECONDS = float(os.environ.get('ONLINE_TIMEOUT_SECONDS', '8'))
ONLINE_MAX_RESULTS = int(os.environ.get('ONLINE_MAX_RESULTS', '4'))
ONLINE_MAX_CONTEXT_CHARS = int(os.environ.get('ONLINE_MAX_CONTEXT_CHARS', '6000'))
SEARXNG_BASE_URL = os.environ.get('SEARXNG_BASE_URL', 'http://127.0.0.1:8888')

# Optional ESP32 action/sensor integration over a local MQTT broker.
DEVICE_CONTROL_ENABLED = os.environ.get('DEVICE_CONTROL_ENABLED', 'false').lower() in ('1', 'true', 'yes', 'on')
DEVICE_TRANSPORT = os.environ.get('DEVICE_TRANSPORT', 'mqtt')
MQTT_HOST = os.environ.get('MQTT_HOST', '127.0.0.1')
MQTT_PORT = int(os.environ.get('MQTT_PORT', '1883'))
MQTT_KEEPALIVE = int(os.environ.get('MQTT_KEEPALIVE', '30'))
MQTT_COMMAND_TIMEOUT_SECONDS = float(os.environ.get('MQTT_COMMAND_TIMEOUT_SECONDS', '5'))
MQTT_TOPIC_PREFIX = os.environ.get('MQTT_TOPIC_PREFIX', 'smart-companion')
ESP32_DEVICE_ID = os.environ.get('ESP32_DEVICE_ID', '')

# First-boot Wi-Fi provisioning. A deployment must supply a unique WPA2
# passphrase; there is intentionally no source-controlled fallback secret.
SETUP_AP_PASSWORD = os.environ.get('SETUP_AP_PASSWORD', '')
SETUP_SAVED_PROFILE_ATTEMPTS = int(os.environ.get('SETUP_SAVED_PROFILE_ATTEMPTS', '5'))
SETUP_CONNECT_COOLDOWN_SECONDS = int(os.environ.get('SETUP_CONNECT_COOLDOWN_SECONDS', '5'))
COMPANION_CANONICAL_URL = 'http://smart-ai-companion.local:8000/'

# Resource-aware edge manager policy. These Raspberry Pi-oriented defaults are
# deliberately conservative and drive recommendations only; V1 performs no
# model, service, CPU, fan, storage, or networking mutations.
RESOURCE_CPU_CAUTION_PERCENT = 80.0
RESOURCE_CPU_CONSTRAINED_PERCENT = 95.0
RESOURCE_LOAD_CAUTION_PER_CPU = 1.0
RESOURCE_LOAD_CONSTRAINED_PER_CPU = 1.5
RESOURCE_MEMORY_CAUTION_PERCENT = 80.0
RESOURCE_MEMORY_CONSTRAINED_PERCENT = 90.0
RESOURCE_MEMORY_CRITICAL_PERCENT = 95.0
RESOURCE_STORAGE_CAUTION_PERCENT = 85.0
RESOURCE_STORAGE_CRITICAL_PERCENT = 95.0
RESOURCE_STORAGE_CAUTION_FREE_BYTES = 5 * 1024 ** 3
RESOURCE_STORAGE_CRITICAL_FREE_BYTES = 1 * 1024 ** 3
RESOURCE_TEMP_CAUTION_C = 65.0
RESOURCE_TEMP_CONSTRAINED_C = 75.0
RESOURCE_TEMP_CRITICAL_C = 80.0
RESOURCE_PERFORMANCE_CPU_MAX_PERCENT = 40.0
RESOURCE_PERFORMANCE_MEMORY_MAX_PERCENT = 65.0
RESOURCE_PERFORMANCE_STORAGE_MAX_PERCENT = 75.0
RESOURCE_PERFORMANCE_TEMP_MAX_C = 60.0
RESOURCE_MANAGER_CACHE_SECONDS = 5

# Voice Engine Configuration
STT_ENGINE = os.environ.get('STT_ENGINE', 'mock')
STT_WHISPER_BIN = os.environ.get('STT_WHISPER_BIN', '/opt/whisper.cpp/main')
STT_WHISPER_MODEL = os.environ.get('STT_WHISPER_MODEL', '/opt/whisper.cpp/models/ggml-base.en.bin')
STT_TIMEOUT = int(os.environ.get('STT_TIMEOUT', '30'))
STT_VAD_ENABLED = os.environ.get('STT_VAD_ENABLED', 'false').lower() in ('1', 'true', 'yes', 'on')
STT_VAD_MODEL = os.environ.get('STT_VAD_MODEL', '')
STT_VAD_THRESHOLD = float(os.environ.get('STT_VAD_THRESHOLD', '0.5'))
STT_VAD_MIN_SPEECH_MS = int(os.environ.get('STT_VAD_MIN_SPEECH_MS', '250'))
STT_VAD_MIN_SILENCE_MS = int(os.environ.get('STT_VAD_MIN_SILENCE_MS', '700'))
STT_VAD_SPEECH_PAD_MS = int(os.environ.get('STT_VAD_SPEECH_PAD_MS', '100'))

TTS_ENGINE = os.environ.get('TTS_ENGINE', 'mock')
TTS_PIPER_BIN = os.environ.get('TTS_PIPER_BIN', '/opt/piper/piper')
TTS_PIPER_VOICE = os.environ.get('TTS_PIPER_VOICE', '/opt/piper/en_US-lessac-medium.onnx')
TTS_TIMEOUT = int(os.environ.get('TTS_TIMEOUT', '30'))

# Standalone Raspberry Pi voice loop
COMPANION_DISPLAY_ENABLED = os.environ.get('COMPANION_DISPLAY_ENABLED', 'false').lower() in ('1', 'true', 'yes', 'on')
COMPANION_DISPLAY_PORT = os.environ.get('COMPANION_DISPLAY_PORT', '')
COMPANION_DISPLAY_BAUD = os.environ.get('COMPANION_DISPLAY_BAUD', '115200')
COMPANION_DISPLAY_STARTUP_DELAY_SECONDS = os.environ.get('COMPANION_DISPLAY_STARTUP_DELAY_SECONDS', '1.5')

VOICE_INPUT_SOURCE = os.environ.get('VOICE_INPUT_SOURCE', '')
VOICE_RECORD_SECONDS = os.environ.get('VOICE_RECORD_SECONDS', '5')
VOICE_INPUT_WARMUP_SECONDS = os.environ.get('VOICE_INPUT_WARMUP_SECONDS', '1.0')
VOICE_CAPTURE_VAD_ENABLED = os.environ.get('VOICE_CAPTURE_VAD_ENABLED', 'false').lower() in ('1', 'true', 'yes', 'on')
VOICE_CAPTURE_VAD_START_THRESHOLD = os.environ.get('VOICE_CAPTURE_VAD_START_THRESHOLD', '0.02')
VOICE_CAPTURE_VAD_SILENCE_SECONDS = os.environ.get('VOICE_CAPTURE_VAD_SILENCE_SECONDS', '0.8')
VOICE_CAPTURE_VAD_MAX_SECONDS = os.environ.get('VOICE_CAPTURE_VAD_MAX_SECONDS', '10')
VOICE_CAPTURE_VAD_START_TIMEOUT_SECONDS = os.environ.get('VOICE_CAPTURE_VAD_START_TIMEOUT_SECONDS', '5')
VOICE_LEADING_SILENCE_SECONDS = os.environ.get('VOICE_LEADING_SILENCE_SECONDS', '0.7')
VOICE_TTS_CHUNK_CHARS = os.environ.get('VOICE_TTS_CHUNK_CHARS', '300')
VOICE_TTS_MAX_TOTAL_CHARS = os.environ.get('VOICE_TTS_MAX_TOTAL_CHARS', '0')
VOICE_LLM_BRIEF_NUM_PREDICT = os.environ.get('VOICE_LLM_BRIEF_NUM_PREDICT', '96')
VOICE_LLM_NORMAL_NUM_PREDICT = os.environ.get('VOICE_LLM_NORMAL_NUM_PREDICT', '160')
VOICE_LLM_DETAILED_NUM_PREDICT = os.environ.get('VOICE_LLM_DETAILED_NUM_PREDICT', '384')
